### ISSUE TITLE
Install instruction on 'release' page have a wrong path to the installer script

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry-community/traveling-bosh#2]
On the [release page](https://github.com/cloudfoundry-community/traveling-bosh/releases), the instructions to use the installer script have a wrong path to the installer script. 

The command currently reads:
`curl -k -s https://raw.githubusercontent.com/cloudfoundry-community/bosh_cli_install/master/binscripts/installer | bash`

but it should be 
`curl -k -s https://raw.githubusercontent.com/cloudfoundry-community/bosh_cli_install/master/scripts/installer | bash`

**Comment by jhunt** [comment]
FWIW, I updated the release descriptions.
