### ISSUE TITLE
Terraform version is fairly ancient...

### ISSUE THREAD

**Issue by mstine** [cloudfoundry-community/traveling-bosh#9]
https://github.com/cloudfoundry-community/traveling-bosh/blob/a6e14b4a4b5dd689d2557eae7f4e13e5cc73b909/Rakefile#L28 specifies 0.3.6. Terraform is now at 0.6.3.

I would fix this myself and submit a PR, but don't have time at the moment.

**Comment by drnic** [comment]
I broke the build system for making new patched bosh_cli that goes into
traveling-bosh; and so I stopped making them. I'll try to make time to fix
it soon; then it will start distributing new terraform.
